#!/bin/sh
# Statusbar for DWM

status_cache_file="$XDG_CACHE_HOME/dwmstatus"
module_separator=" | "

[ ! -f "$status_cache_file" ] && touch "$status_cache_file"

xsetroot -name "$(cut -d'|' -f2- "$status_cache_file" | tr '\n' '\r' | sed "s/\r/$module_separator/g;s/$module_separator$//")"
